### ISSUE TITLE
Questions about MIDI 2.0 implementation

### ISSUE THREAD

**Issue by philburk** [atsushieno/kmmk#9]
You mention MIDI 2.0 support. Congratulations! This is one of the first apps to do so. 
I have some questions.

By MIDI 2.0 do you mean MIDI-CI or Universal MIDI Packet or both?

Where is the code that implements the MIDI 2.0? I looked but could not find it?

**Comment by philburk** [comment]
I found https://github.com/atsushieno/ktmidi
and answered my own questions.

**Comment by atsushieno** [comment]
Thanks for the note. Yes, ktmidi is the library that implements UMP and CI stuff. (CI support is quite incomplete, as I don't have any device and use cases yet.)

This application currently deals with hacky and unconfirmed use of MICI-CI packets to enable MIDI 2.0 mode without pairing an input and an output - it only sends Set New Protocol message, and does not deal with any confirmation. I believe the upcoming MIDI 2.0 spec. ([mentioned here](https://www.midi.org/midi-articles/details-about-midi-2-0-midi-ci-profiles-and-property-exchange)) will simplify this part and I leave it as is so far.
